[versions]
exposed = "0.44.1"
h2 = "2.2.224"
hikariCp = "5.1.0"
flyway = "10.10.0"
logback = "1.4.14"
ktor = "2.3.9"
kotlin = "1.9.23"
kotlinx-datetime = "0.6.0-RC.2"
postgresql = "42.7.3"
koin = "3.5.3"
apacheKafka = "3.4.0"

[libraries]
ktor-serializationKotlinx = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-server-coreJvm = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-contentNegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors-jvm", version.ref = "ktor" }
ktor-server-swagger = { group = "io.ktor", name = "ktor-server-swagger-jvm", version.ref = "ktor" }
ktor-server-openapi = { group = "io.ktor", name = "ktor-server-openapi", version.ref = "ktor" }
ktor-server-hostCommonJvm = { group = "io.ktor", name = "ktor-server-host-common-jvm", version.ref = "ktor" }
ktor-server-statusPages = { group = "io.ktor", name = "ktor-server-status-pages-jvm", version.ref = "ktor" }
ktor-server-nettyJvm = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-testsJvm = { group = "io.ktor", name = "ktor-server-tests-jvm", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
kotlin-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
hikariCp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCp" }
flyway = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-loggerSlf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
apacheKafka = { group = "org.apache.kafka", name = "kafka-clients", version.ref = "apacheKafka" }

[bundles]
ktor-server = ["ktor-server-coreJvm", "ktor-server-contentNegotiation", "ktor-server-cors", "ktor-server-swagger", "ktor-server-openapi", "ktor-server-hostCommonJvm", "ktor-server-statusPages", "ktor-server-nettyJvm"]
ktor-client = ["ktor-client-core", "ktor-client-contentNegotiation", "ktor-client-cio"]
exposed = ["exposed-core", "exposed-jdbc"]
koin = ["koin-ktor", "koin-loggerSlf4j"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }